name: Check and Build

on:
  push:
    branches:
      - "multiple"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get_tags:
    runs-on: ubuntu-latest
    outputs:
      nginx_tags: ${{ steps.nginx.outputs.tags }}
    steps:
      - name: Find latest nginx release tags
        id: nginx
        uses: hakwerk/gha-git-repo-tags@v1
        with:
          repository: nginx/nginx
          limit: 5
          reverse: true

  prepare:
    needs: get_tags
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nginx_tag: ${{ fromJson( needs.get_tags.outputs.nginx_tags ) }}
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - uses: hakwerk/do-build@multiple
        with:
          nginx_tag: ${{ matrix.nginx_tag }}
          platform: ${{ matrix.platform }}

