name: Check and Build

on:
  push:
    branches:
      - "multiple"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get_tags:
    runs-on: ubuntu-latest
    outputs:
      nginx_tags: ${{ steps.nginx.outputs.tags }}
    steps:
      - name: Find latest nginx release tags
        id: nginx
        uses: oraad/get-tags-action@v1.0.0
        with:
          repo: nginx/nginx
          limit: 5

  prepare:
    needs: get_tags
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nginx_tag: ${{ needs.job1.outputs.nginx_tags }}
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: debug
        run: echo ${{ matrix.nginx_tag }}
      - name: debug
        run: echo ${{ matrix.platform }}

