name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check image
        id: image_exists
        uses: cloudposse/github-action-docker-image-exists@main
        with:
          registry: registry.hub.docker.com
          organization: "${{ github.event.repository.owner.login }}"
          repository: "${{ github.event.repository.name }}"
          tag: 1.25.3

      - name: Show result
        run: |
          echo "** result is ${{ steps.image_exists.conclusion }}"
          echo "** image is ${{ steps.image_exists.outputs.image }}"
          echo "** tag is ${{ steps.image_exists.outputs.tag }}"

      - name: Check image not exists
        id: image_not_exists
        uses: cloudposse/github-action-docker-image-exists@main
        with:
          registry: registry.hub.docker.com
          organization: "${{ github.event.repository.owner.login }}"
          repository: "${{ github.event.repository.name }}"
          tag: 1.2.3
        continue-on-error: true

      - name: Show result
        run: |
          echo "** result is ${{ steps.image_not_exists.conclusion }}"
          echo "** image is ${{ steps.image_not_exists.outputs.image }}"
          echo "** tag is ${{ steps.image_not_exists.outputs.tag }}"

